# Generated by Django 3.2.5 on 2021-10-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bike_state', models.IntegerField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('role', models.IntegerField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('balance', models.FloatField()),
                ('user_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('payment_time', models.TimeField()),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharesystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rent_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('return_time', models.TimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharesystem.bike')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharesystem.payment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharesystem.user')),
            ],
        ),
    ]
