# Generated by Django 3.2.5 on 2021-10-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
