# Generated by Django 3.2.5 on 2021-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_state',
            field=models.IntegerField(default=0),
        ),
    ]
