# Generated by Django 3.2.8 on 2021-10-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0003_auto_20211026_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=0),
        ),
    ]
