# Generated by Django 3.2.8 on 2021-10-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0004_auto_20211028_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rent_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('defect_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('report_time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharesystem.bike')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharesystem.myuser')),
            ],
        ),
    ]
