# Generated by Django 3.2.8 on 2021-10-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0005_auto_20211029_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharesystem.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
