# Generated by Django 3.2.8 on 2021-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0006_auto_20211030_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_state',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'in use')], default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'manager'), (1, 'operator'), (2, 'customer')], default=2),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_state',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'riding')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'ongoing'), (1, 'unpaid'), (2, 'finished')], default=0),
        ),
    ]
