# Generated by Django 3.2.8 on 2021-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0007_auto_20211030_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_state',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'in use'), (2, 'broken')], default=0),
        ),
    ]
