# Generated by Django 3.2.5 on 2021-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesystem', '0008_alter_bike_bike_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_state',
            field=models.IntegerField(default=0),
        ),
    ]
